name: GitHub Readme Stats
on:
  workflow_dispatch:
  schedule:
  - cron: 0 */24 * * *

jobs:
  grs:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Top Languages Card
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Stats
        uses: Zo-Bro-23/grs-action@v1
        id: generate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          options: 'username=${{ github.repository_owner }}&layout=compact&langs_count=20&disable_animations=true&theme=graywhite&hide=qml,latte,cmake,glsl,hack,scss,objective-c,ruby,starlark,emacs%20lisp,swift,html,c%2B%2B,jupyter%20notebook,haskell,blade,dart,css'
          card: 'top-langs'
      - name: Push
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: grs
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
